CREATE TABLE "transactions" (
	"id" varchar PRIMARY KEY NOT NULL,
	"fecha" date NOT NULL,
	"tramite" varchar NOT NULL,
	"matricula" varchar,
	"pagado" boolean DEFAULT false NOT NULL,
	"boleta" boolean DEFAULT false NOT NULL,
	"boletas_registradas" numeric(12, 2) NOT NULL,
	"emitido_por" varchar NOT NULL,
	"placa" varchar NOT NULL,
	"tipo_documento" varchar NOT NULL,
	"numero_documento" varchar NOT NULL,
	"nombre" varchar NOT NULL,
	"cilindraje" integer,
	"tipo_vehiculo" varchar,
	"celular" varchar,
	"ciudad" varchar NOT NULL,
	"asesor" varchar NOT NULL,
	"novedad" varchar,
	"precio_neto" numeric(12, 2) NOT NULL,
	"comision_extra" boolean DEFAULT false NOT NULL,
	"tarifa_servicio" numeric(12, 2) NOT NULL,
	"impuesto_4x1000" numeric(12, 2) NOT NULL,
	"ganancia_bruta" numeric(12, 2) NOT NULL,
	"rappi" boolean DEFAULT false NOT NULL,
	"observaciones" varchar
);
